version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PROXY_DOMAIN=code.rubenshaw.com
    volumes:
      - /home/delta/code:/config
    ports:
      - 8888:8443
    restart: unless-stopped
