---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/docker/

Delta:
  socket: /var/run/docker.sock
Echo:
  host: 192.168.0.201
  port: 2375
Kilo:
  host: 192.168.0.202
  port: 2375
